### PR TITLE
Use monaco editor (VSCode) instead of react-lazylog

### PR DESCRIPTION
**Pull request by driazati**
react-lazylog is an abandoned mozilla project (https://github.com/mozilla-frontend-infra/react-lazylog) with some limitations pointed out by @suo. This integrates a real text editor which should make browsing the logs on the PR page more familiar and powerful.

https://deploy-preview-109--pytorch-ci-hud.netlify.app/commit/f767cf668395baf29ca7c9f1fa80f0abed8c53c7

image

### CODE REVIEW

**Comment by ezyang** [comment]
I don't understand why we are using a text editor to browse logs

**Comment by driazati** [comment]
> I don't understand why we are using a text editor to browse logs

We need something that has good search and pagination of lines (loading 100k+ lines in a `<pre>` doesn’t really work too good), this is an easy and familiar way to get that. We could make it not be a text editor by setting `readOnly: true`, but I don’t see why we should remove functionality that is entirely opt in

**Comment by ezyang** [comment]
> loading 100k+ lines in a <pre> doesn’t really work too good

idk, worked pretty good for Jenkins. Much more important to make sure the browser isn't doing extra work reflowing the page or chewing up CPU for stuff that doesn't matter.

**Review by seemethere — APPROVED** [review]

**Comment by seemethere** [comment]
> > loading 100k+ lines in a  doesn’t really work too good
> 
> idk, worked pretty good for Jenkins. Much more important to make sure the browser isn't doing extra work reflowing the page or chewing up CPU for stuff that doesn't matter.

Doesn't Jenkins do truncation if reading logs through the UI?

**Comment by ezyang** [comment]
sure, but it gives you enough lines that usually what you need to find is there

**Comment by suo** [comment]
> sure, but it gives you enough lines that usually what you need to find is there

not if we are running all tests and the failure is somewhere in the middle :/ we should really reconsider that

**Comment by driazati** [comment]
This PR solves the UX problem pretty completely and from checking it against the current log viewer it's about the same in CPU usage when scrolling around the logs so it seems like we should merge this

**Comment by Psoffie009** [comment]
> react-lazylog is an abandoned mozilla project (https://github.com/mozilla-frontend-infra/react-lazylog) with some limitations pointed out by @suo. This integrates a real text editor which should make browsing the logs on the PR page more familiar and powerful.
> 
> https://deploy-preview-109--pytorch-ci-hud.netlify.app/commit/f767cf668395baf29ca7c9f1fa80f0abed8c53c7
> 
> image

**Pull request merged**
